var namespacepugi =
[
    [ "xml_attribute", "classpugi_1_1xml__attribute.html", "classpugi_1_1xml__attribute" ],
    [ "xml_attribute_iterator", "classpugi_1_1xml__attribute__iterator.html", "classpugi_1_1xml__attribute__iterator" ],
    [ "xml_attribute_struct", "structpugi_1_1xml__attribute__struct.html", "structpugi_1_1xml__attribute__struct" ],
    [ "xml_document", "classpugi_1_1xml__document.html", "classpugi_1_1xml__document" ],
    [ "xml_named_node_iterator", "classpugi_1_1xml__named__node__iterator.html", "classpugi_1_1xml__named__node__iterator" ],
    [ "xml_node", "classpugi_1_1xml__node.html", "classpugi_1_1xml__node" ],
    [ "xml_node_iterator", "classpugi_1_1xml__node__iterator.html", "classpugi_1_1xml__node__iterator" ],
    [ "xml_node_struct", "structpugi_1_1xml__node__struct.html", "structpugi_1_1xml__node__struct" ],
    [ "xml_object_range", "classpugi_1_1xml__object__range.html", "classpugi_1_1xml__object__range" ],
    [ "xml_parse_result", "structpugi_1_1xml__parse__result.html", "structpugi_1_1xml__parse__result" ],
    [ "xml_text", "classpugi_1_1xml__text.html", "classpugi_1_1xml__text" ],
    [ "xml_tree_walker", "classpugi_1_1xml__tree__walker.html", "classpugi_1_1xml__tree__walker" ],
    [ "xml_writer", "classpugi_1_1xml__writer.html", "classpugi_1_1xml__writer" ],
    [ "xml_writer_file", "classpugi_1_1xml__writer__file.html", "classpugi_1_1xml__writer__file" ],
    [ "xml_writer_stream", "classpugi_1_1xml__writer__stream.html", "classpugi_1_1xml__writer__stream" ],
    [ "xpath_exception", "classpugi_1_1xpath__exception.html", "classpugi_1_1xpath__exception" ],
    [ "xpath_node", "classpugi_1_1xpath__node.html", "classpugi_1_1xpath__node" ],
    [ "xpath_node_set", "classpugi_1_1xpath__node__set.html", "classpugi_1_1xpath__node__set" ],
    [ "xpath_parse_result", "structpugi_1_1xpath__parse__result.html", "structpugi_1_1xpath__parse__result" ],
    [ "xpath_query", "classpugi_1_1xpath__query.html", "classpugi_1_1xpath__query" ],
    [ "xpath_variable", "classpugi_1_1xpath__variable.html", "classpugi_1_1xpath__variable" ],
    [ "xpath_variable_set", "classpugi_1_1xpath__variable__set.html", "classpugi_1_1xpath__variable__set" ]
];